sonar.projectKey=Kotlin
sonar.qualitygate.wait=true

sonar.exclusions=**/presentation/**/*.kt,**/*Activity.kt,**/*Application.kt,**/components/**/*.kt

sonar.coverage.exclusions=**/presentation/**/*.kt,**/*Activity.kt,**/*Application.kt,**/components/**/*.kt,**/*Screen.kt
